package enums;

public enum Endpoint {
    GET_TASKS,
    GET_EPICS,
    GET_SUBTASKS,
    GET_TASK,
    GET_EPIC,
    GET_SUBTASK,
    POST_TASK,
    POST_EPIC,
    POST_SUBTASK,
    DELETE_TASK,
    DELETE_EPIC,
    DELETE_SUBTASK,
    GET_EPICS_SUBTASK,
    GET_HISTORY,
    GET_PRIORITIZED_TASKS,
    UNKNOWN
}
